// Ordem de carregamento dos módulos do jogo.
// A ordem TEM de ser respeitada: os ficheiros partilham o mesmo escopo global
// (são carregados como scripts clássicos) e foram divididos a partir do
// antigo main.js monolítico mantendo a sequência original de execução.
export const MODULOS_JOGO = [
    "src/core/globals.js",
    "src/manager/manager-modo.js",
    "src/online/multiplayer.js",
    "src/core/estado.js",
    "src/core/elenco-titulares.js",
    "src/core/save-load.js",
    "src/competicoes/zonas-qualificacao.js",
    "src/dados/premios-e-selecoes.js",
    "src/core/calendario.js",
    "src/selecoes/selecoes-internacional.js",
    "src/ui/estilos.js",
    "src/utils/imagens-e-valores.js",
    "src/negociacoes/negociacoes.js",
    "src/ui/navegacao.js",
    "src/partida/simulacao-visual.js",
    "src/ui/audio.js",
    "src/nucleo/noticias.js",
    "src/selecoes/convocacoes.js",
    "src/ui/temas-e-conquistas.js",
    "src/jogador/carreira.js",
    "src/ui/perfis-e-pesquisa.js",
    "src/mercado/mercado-transferencias.js",
    "src/ui/telas-jogador.js",
    "src/nucleo/eventos-e-atributos.js",
    "src/competicoes/copas-e-grupos.js",
    "src/simulacao/simulacao-rodada.js",
    "src/temporada/fim-temporada.js",
    "src/tecnicos/treinadores.js",
    "src/manager/manager-core.js",
    "src/manager/manager-ui.js",
    "src/ui/hub-e-tabelas.js",
    "src/ui/interacoes-hub.js",
    "src/treino/treino-modal.js",
    "src/partida/penaltis-e-pos-partida.js",
    "src/ui/criacao-manager.js",
    "src/online/lobby-pregame.js",
    "src/jogador/criacao-atributos.js",
    "src/jogador/treino-e-lifestyle.js",
    "src/partida/penalti-minigame-ui.js",
    "src/jogador/interacao-tecnico.js",
];
